# ------------------------------------------------------------------------------
# Workflow: Dependency Review
# Purpose:
#       Automatically checks any new or updated dependencies in a pull request
#       for security vulnerabilities or other risks.
#
# Trigger:
#       Whenever a PR is opened, synchronized, or reopened
#
# Notes:
#       Uses GitHub's official Dependency Review action to highlight potential
#       issues before merging.
# ------------------------------------------------------------------------------
name: Dependency Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # ---------------------------
      # Checkout the repository to get the dependencies
      # ---------------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------------------
      # Runs github's dependency check
      # ---------------------------
      - name: Dependency check
        uses: actions/dependency-review-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}