# ------------------------------------------------------------------------------
# Workflow: Check Dependencies
# Purpose:
#     Check the status of the upstream jobs.
#
# Trigger:
#   Invoked by services via "workflow_call".
#
# Notes:
#   - If ANY upstream job failed or was cancelled → this workflow fails.
#   - If ALL upstream jobs passed or were skipped → this workflow succeeds.
# ------------------------------------------------------------------------------
name: Check Dependencies

on:
  workflow_call:
    inputs:
      code_quality_status:
        type: string
        required: true
      quality_scan_status:
        type: string
        required: true
      security_scan_status:
        type: string
        required: true
      unit_tests_status:
        type: string
        required: true
      integration_tests_status:
        type: string
        required: true

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      # ---------------------------
      # 1. Checks status of jobs. Fail fast if any job == failure or cancelled.
      # ---------------------------
      - name: Evaluate Upstream Job Results
        run: |
          echo "Evaluating results of all preceding jobs..."

          # Collect all statuses into an array for easy iteration
          JOB_STATUSES=(
            "${{ inputs.code_quality_status }}"
            "${{ inputs.quality_scan_status }}"
            "${{ inputs.security_scan_status }}"
            "${{ inputs.unit_tests_status }}"
            "${{ inputs.integration_tests_status }}"
          )

          FAILURE_DETECTED=false

          for status in "${JOB_STATUSES[@]}"; do
            # Check for failure or cancellation
            if [[ "$status" == "failure" || "$status" == "cancelled" ]]; then
              echo "🔴 FAILURE DETECTED! Job with status '$status' prevents continuation."
              FAILURE_DETECTED=true
              break
            fi
          done

          if [ "$FAILURE_DETECTED" = true ]; then
            exit 1 # Fail this workflow → blocks downstream jobs
          else
            echo "🟢 All required dependencies passed or were intentionally skipped."
          fi
