# ------------------------------------------------------------------------------
# Workflow: Quality Scan
# Purpose:
#   Runs SonarCloud analysis
#
# Trigger:
#   Invoked by other workflows via "workflow_call".
#
# Notes:
#   - SonarCloud analyzes code to identify bugs, code smells, and coverage gaps,
#     and provides a single unified report on the SonarCloud dashboard.
# ------------------------------------------------------------------------------
name: Quality Scan

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      gradle_cache_key:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  quality-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # ---------------------------
      # 1. Check out repository
      # ---------------------------
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # ---------------------------
      # 2. Set up Java 21
      # ---------------------------
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      # ---------------------------
      # 3. Searches GitHub Actions cache storage for an entry matching gradle_cache_key
      #   - If found → restore into ~/.gradle/caches and ~/.gradle/wrapper
      #   - If not found → try restore-keys prefix for partial match
      #   - If still not found → Gradle downloads fresh, saved under key after job
      # ---------------------------
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ inputs.gradle_cache_key }}
          restore-keys: gradle-${{ runner.os }}-

      # ---------------------------
      # 4. Download Jacoco XML for SonarCloud
      # ---------------------------
      - name: Download Unit Test Coverage
        uses: actions/download-artifact@v5
        with:
          name: coverage-xml-${{ inputs.service_name }}
          path: build/reports/jacoco/${{ inputs.service_name }}

      # ---------------------------
      # 5. Rebuild Project (needed for sonar.java.binaries)
      # ---------------------------
      - name: Build Project (No Tests)
        run: ./gradlew build -x test --no-daemon

      # ---------------------------
      # 6. Run SonarCloud Analysis
      # ---------------------------
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=ar-ecommerce-platform_${{ github.event.repository.name }} \
            -Dsonar.organization=ar-ecommerce-platform \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/${{ inputs.service_name }}/coverage.xml
